spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      platform: postgres
      encoding: UTF-8
#      data-locations: classpath:/sql/schema.sql, classpath:/sql/demo_data.sql
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: YXNkYXNkYXNkYWRhc2RzZ25MS1BMUEwnYXNkYXNkYWpzZmFhc2Fhc2Zhc2ZnYXM=
    access: 3600000
    refresh: 2592000000